// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: user.proto

package wechat_user

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// WeChatUserService defines service.
type WeChatUserService interface {
	// UserLogin 用户登陆
	UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

func WeChatUserService_UserLogin_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UserLoginRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(WeChatUserService).UserLogin(ctx, reqbody.(*UserLoginRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func WeChatUserService_GetUserInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserInfoRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(WeChatUserService).GetUserInfo(ctx, reqbody.(*GetUserInfoRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// WeChatUserServer_ServiceDesc descriptor for server.RegisterService.
var WeChatUserServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.wechat.user.WeChatUser",
	HandlerType: ((*WeChatUserService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.wechat.user.WeChatUser/UserLogin",
			Func: WeChatUserService_UserLogin_Handler,
		},
		{
			Name: "/trpc.wechat.user.WeChatUser/GetUserInfo",
			Func: WeChatUserService_GetUserInfo_Handler,
		},
	},
}

// RegisterWeChatUserService registers service.
func RegisterWeChatUserService(s server.Service, svr WeChatUserService) {
	if err := s.Register(&WeChatUserServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("WeChatUser register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedWeChatUser struct{}

// UserLogin 用户登陆
func (s *UnimplementedWeChatUser) UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, errors.New("rpc UserLogin of service WeChatUser is not implemented")
}

// GetUserInfo 获取用户信息
func (s *UnimplementedWeChatUser) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, errors.New("rpc GetUserInfo of service WeChatUser is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// WeChatUserClientProxy defines service client proxy
type WeChatUserClientProxy interface {
	// UserLogin 用户登陆
	UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (rsp *UserLoginResponse, err error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (rsp *GetUserInfoResponse, err error)
}

type WeChatUserClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewWeChatUserClientProxy = func(opts ...client.Option) WeChatUserClientProxy {
	return &WeChatUserClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *WeChatUserClientProxyImpl) UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (*UserLoginResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.wechat.user.WeChatUser/UserLogin")
	msg.WithCalleeServiceName(WeChatUserServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("wechat")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("WeChatUser")
	msg.WithCalleeMethod("UserLogin")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UserLoginResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *WeChatUserClientProxyImpl) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (*GetUserInfoResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.wechat.user.WeChatUser/GetUserInfo")
	msg.WithCalleeServiceName(WeChatUserServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("wechat")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("WeChatUser")
	msg.WithCalleeMethod("GetUserInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserInfoResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
