// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: user.proto

package wechat_user

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// WeChatUserServiceService defines service.
type WeChatUserServiceService interface {
	// UserLogin 用户登陆
	UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

func WeChatUserServiceService_UserLogin_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UserLoginRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(WeChatUserServiceService).UserLogin(ctx, reqbody.(*UserLoginRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func WeChatUserServiceService_GetUserInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetUserInfoRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(WeChatUserServiceService).GetUserInfo(ctx, reqbody.(*GetUserInfoRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// WeChatUserServiceServer_ServiceDesc descriptor for server.RegisterService.
var WeChatUserServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.wechat.user.WeChatUserService",
	HandlerType: ((*WeChatUserServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.wechat.user.WeChatUserService/UserLogin",
			Func: WeChatUserServiceService_UserLogin_Handler,
		},
		{
			Name: "/trpc.wechat.user.WeChatUserService/GetUserInfo",
			Func: WeChatUserServiceService_GetUserInfo_Handler,
		},
	},
}

// RegisterWeChatUserServiceService registers service.
func RegisterWeChatUserServiceService(s server.Service, svr WeChatUserServiceService) {
	if err := s.Register(&WeChatUserServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("WeChatUserService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedWeChatUserService struct{}

// UserLogin 用户登陆
func (s *UnimplementedWeChatUserService) UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	return nil, errors.New("rpc UserLogin of service WeChatUserService is not implemented")
}

// GetUserInfo 获取用户信息
func (s *UnimplementedWeChatUserService) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, errors.New("rpc GetUserInfo of service WeChatUserService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// WeChatUserServiceClientProxy defines service client proxy
type WeChatUserServiceClientProxy interface {
	// UserLogin 用户登陆
	UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (rsp *UserLoginResponse, err error)
	// GetUserInfo 获取用户信息
	GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (rsp *GetUserInfoResponse, err error)
}

type WeChatUserServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewWeChatUserServiceClientProxy = func(opts ...client.Option) WeChatUserServiceClientProxy {
	return &WeChatUserServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *WeChatUserServiceClientProxyImpl) UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (*UserLoginResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.wechat.user.WeChatUserService/UserLogin")
	msg.WithCalleeServiceName(WeChatUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("wechat")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("WeChatUserService")
	msg.WithCalleeMethod("UserLogin")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UserLoginResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *WeChatUserServiceClientProxyImpl) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (*GetUserInfoResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.wechat.user.WeChatUserService/GetUserInfo")
	msg.WithCalleeServiceName(WeChatUserServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("wechat")
	msg.WithCalleeServer("user")
	msg.WithCalleeService("WeChatUserService")
	msg.WithCalleeMethod("GetUserInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetUserInfoResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
