// Code generated by MockGen. DO NOT EDIT.
// Source: user.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=user_mock.go -package=wechat_user --source=user.trpc.go -self_package=github.com/ustcLyric/wechat-trpcprotocol/wechat_user
//

// Package wechat_user is a generated GoMock package.
package wechat_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockWeChatUserService is a mock of WeChatUserService interface.
type MockWeChatUserService struct {
	ctrl     *gomock.Controller
	recorder *MockWeChatUserServiceMockRecorder
	isgomock struct{}
}

// MockWeChatUserServiceMockRecorder is the mock recorder for MockWeChatUserService.
type MockWeChatUserServiceMockRecorder struct {
	mock *MockWeChatUserService
}

// NewMockWeChatUserService creates a new mock instance.
func NewMockWeChatUserService(ctrl *gomock.Controller) *MockWeChatUserService {
	mock := &MockWeChatUserService{ctrl: ctrl}
	mock.recorder = &MockWeChatUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeChatUserService) EXPECT() *MockWeChatUserServiceMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockWeChatUserService) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockWeChatUserServiceMockRecorder) GetUserInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockWeChatUserService)(nil).GetUserInfo), ctx, req)
}

// UserLogin mocks base method.
func (m *MockWeChatUserService) UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogin", ctx, req)
	ret0, _ := ret[0].(*UserLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockWeChatUserServiceMockRecorder) UserLogin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockWeChatUserService)(nil).UserLogin), ctx, req)
}

// MockWeChatUserClientProxy is a mock of WeChatUserClientProxy interface.
type MockWeChatUserClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockWeChatUserClientProxyMockRecorder
	isgomock struct{}
}

// MockWeChatUserClientProxyMockRecorder is the mock recorder for MockWeChatUserClientProxy.
type MockWeChatUserClientProxyMockRecorder struct {
	mock *MockWeChatUserClientProxy
}

// NewMockWeChatUserClientProxy creates a new mock instance.
func NewMockWeChatUserClientProxy(ctrl *gomock.Controller) *MockWeChatUserClientProxy {
	mock := &MockWeChatUserClientProxy{ctrl: ctrl}
	mock.recorder = &MockWeChatUserClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeChatUserClientProxy) EXPECT() *MockWeChatUserClientProxyMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockWeChatUserClientProxy) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfo", varargs...)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockWeChatUserClientProxyMockRecorder) GetUserInfo(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockWeChatUserClientProxy)(nil).GetUserInfo), varargs...)
}

// UserLogin mocks base method.
func (m *MockWeChatUserClientProxy) UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (*UserLoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UserLogin", varargs...)
	ret0, _ := ret[0].(*UserLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockWeChatUserClientProxyMockRecorder) UserLogin(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockWeChatUserClientProxy)(nil).UserLogin), varargs...)
}
