// Code generated by MockGen. DO NOT EDIT.
// Source: user.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=user_mock.go -package=wechat_user --source=user.trpc.go -self_package=github.com/ustcLyric/wechat-trpcprotocol/wechat_user
//

// Package wechat_user is a generated GoMock package.
package wechat_user

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockWeChatUserServiceService is a mock of WeChatUserServiceService interface.
type MockWeChatUserServiceService struct {
	ctrl     *gomock.Controller
	recorder *MockWeChatUserServiceServiceMockRecorder
	isgomock struct{}
}

// MockWeChatUserServiceServiceMockRecorder is the mock recorder for MockWeChatUserServiceService.
type MockWeChatUserServiceServiceMockRecorder struct {
	mock *MockWeChatUserServiceService
}

// NewMockWeChatUserServiceService creates a new mock instance.
func NewMockWeChatUserServiceService(ctrl *gomock.Controller) *MockWeChatUserServiceService {
	mock := &MockWeChatUserServiceService{ctrl: ctrl}
	mock.recorder = &MockWeChatUserServiceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeChatUserServiceService) EXPECT() *MockWeChatUserServiceServiceMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockWeChatUserServiceService) GetUserInfo(ctx context.Context, req *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, req)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockWeChatUserServiceServiceMockRecorder) GetUserInfo(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockWeChatUserServiceService)(nil).GetUserInfo), ctx, req)
}

// UserLogin mocks base method.
func (m *MockWeChatUserServiceService) UserLogin(ctx context.Context, req *UserLoginRequest) (*UserLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogin", ctx, req)
	ret0, _ := ret[0].(*UserLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockWeChatUserServiceServiceMockRecorder) UserLogin(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockWeChatUserServiceService)(nil).UserLogin), ctx, req)
}

// MockWeChatUserServiceClientProxy is a mock of WeChatUserServiceClientProxy interface.
type MockWeChatUserServiceClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockWeChatUserServiceClientProxyMockRecorder
	isgomock struct{}
}

// MockWeChatUserServiceClientProxyMockRecorder is the mock recorder for MockWeChatUserServiceClientProxy.
type MockWeChatUserServiceClientProxyMockRecorder struct {
	mock *MockWeChatUserServiceClientProxy
}

// NewMockWeChatUserServiceClientProxy creates a new mock instance.
func NewMockWeChatUserServiceClientProxy(ctrl *gomock.Controller) *MockWeChatUserServiceClientProxy {
	mock := &MockWeChatUserServiceClientProxy{ctrl: ctrl}
	mock.recorder = &MockWeChatUserServiceClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeChatUserServiceClientProxy) EXPECT() *MockWeChatUserServiceClientProxyMockRecorder {
	return m.recorder
}

// GetUserInfo mocks base method.
func (m *MockWeChatUserServiceClientProxy) GetUserInfo(ctx context.Context, req *GetUserInfoRequest, opts ...client.Option) (*GetUserInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserInfo", varargs...)
	ret0, _ := ret[0].(*GetUserInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockWeChatUserServiceClientProxyMockRecorder) GetUserInfo(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockWeChatUserServiceClientProxy)(nil).GetUserInfo), varargs...)
}

// UserLogin mocks base method.
func (m *MockWeChatUserServiceClientProxy) UserLogin(ctx context.Context, req *UserLoginRequest, opts ...client.Option) (*UserLoginResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UserLogin", varargs...)
	ret0, _ := ret[0].(*UserLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockWeChatUserServiceClientProxyMockRecorder) UserLogin(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockWeChatUserServiceClientProxy)(nil).UserLogin), varargs...)
}
